-- 코드를 입력하세요
SELECT
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(BS.sales * B.price) AS TOTAL_SALES
FROM BOOK AS B
JOIN AUTHOR AS A
ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN BOOK_SALES AS BS
ON B.BOOK_ID = BS.BOOK_ID
WHERE sales_date LIKE "%2022-01%"
GROUP BY A.AUTHOR_NAME , B.CATEGORY
ORDER BY A.AUTHOR_ID ASC , B.CATEGORY DESC