-- 코드를 입력하세요
SELECT
    CP.CART_ID
FROM(
SELECT 
    CART_ID
FROM CART_PRODUCTS
WHERE NAME = 'Milk'
) AS Milk_T
JOIN CART_PRODUCTS AS CP
ON Milk_T.CART_ID = CP.CART_ID
WHERE NAME = 'Yogurt'
GROUP BY CP.CART_ID