SELECT
    YEAR(OS.SALES_DATE) AS YEAR,
    MONTH(OS.SALES_DATE) AS MONTH,
    COUNT(DISTINCT OS.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT OS.USER_ID) / total.total_cnt, 1) AS PUCHASED_RATIO
FROM ONLINE_SALE AS OS
JOIN (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
) AS joined_users
  ON OS.USER_ID = joined_users.USER_ID
JOIN (
    SELECT COUNT(*) AS total_cnt
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
) AS total
GROUP BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE)
ORDER BY YEAR, MONTH;