-- 코드를 입력하세요
SELECT
 FP.PRODUCT_ID,
 FP.PRODUCT_NAME,
 SUM(FP.PRICE * FO.AMOUNT)AS TOTAL_SALES
FROM FOOD_ORDER AS FO
JOIN FOOD_PRODUCT AS FP
ON FO.PRODUCT_ID = FP.PRODUCT_ID
WHERE PRODUCE_DATE LIKE '%2022-05%'
GROUP BY PRODUCT_ID
ORDER BY SUM(FP.PRICE * FO.AMOUNT) DESC, FP.PRODUCT_ID ASC;