WITH A AS (
    SELECT 
        MEMBER_ID, 
        COUNT(*) AS CNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
),
TopReviewers AS (
    SELECT 
        MEMBER_ID, 
        CNT,
        DENSE_RANK() OVER (ORDER BY CNT DESC) AS RNK
    FROM A
)
SELECT 
    # TR.CNT,
    # MP.MEMBER_ID,
    MP.MEMBER_NAME,
    RR.REVIEW_TEXT,
    DATE_FORMAT(RR.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM TopReviewers TR
JOIN REST_REVIEW RR ON TR.MEMBER_ID = RR.MEMBER_ID
JOIN MEMBER_PROFILE MP ON TR.MEMBER_ID = MP.MEMBER_ID
WHERE TR.RNK = 1
ORDER BY RR.REVIEW_DATE ,RR.REVIEW_TEXT;