WITH A AS
(
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT
    B.YEAR,
    A.MAX_SIZE -  B.SIZE_OF_COLONY  AS YEAR_DEV,
    B.ID
FROM
(
    SELECT
        ID,
        SIZE_OF_COLONY,
        YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA 
) AS B
JOIN A ON B.YEAR = A.YEAR
ORDER BY YEAR,YEAR_DEV 
