-- 코드를 입력하세요
SELECT
    DISTINCT(CRCC.car_id)
FROM CAR_RENTAL_COMPANY_CAR AS CRCC
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCRH
ON CRCC.CAR_ID = CRCRH.CAR_ID
WHERE CRCC.car_type = '세단' AND CRCRH.start_date LIKE '2022-10%'
ORDER BY CRCC.car_id DESC