SELECT
    FI.ID,FNI.FISH_NAME,FI.LENGTH
FROM FISH_INFO FI
JOIN FISH_NAME_INFO FNI 
ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE LENGTH=(
    SELECT 
    MAX(LENGTH)
    FROM FISH_INFO
    WHERE FISH_TYPE = FI.FISH_TYPE AND LENGTH > 10
)
ORDER BY FI.ID ASC